# Generated by Django 5.0 on 2023-12-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_content', '0002_alter_post_options_post_author_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_pic',
            field=models.ImageField(null=True, upload_to='author_imgs', verbose_name='Blog Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='blog_imgs', verbose_name='Blog Image'),
        ),
    ]
